source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NNSoundPlayer_Example', :exclusive => true do
  pod 'NNSoundPlayer', :path => '../'
end

target 'NNSoundPlayer_Tests', :exclusive => true do
  pod 'NNSoundPlayer', :path => '../'

  
end
